### PR TITLE
Updating dev dependencies 

### PR DESCRIPTION
**Pull request by NandoCabralss**
I also think it would be nice to change the default branch to main in order to avoid [racially-loaded](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/) terms.

### CODE REVIEW

**Comment by rwillians** [comment]
@NandoCabralss this is looking good, but I'll wait for merging the CI PR first so that we can see it in action ;)

**Comment by rwillians** [comment]
Fixes #24

**Comment by Dlewis89** [comment]
Hey @rwillians, Is a update of the dependencies for the project still needed?

**Comment by rwillians** [comment]
Hey @Dlewis89, not really. Thanks tho.
@NandoCabralss already updated them and they aren’t really critical cuz this project only has dev dependencies.

I’m taking some time off but once I get back I should get these PRs merged and published

**Comment by Dlewis89** [comment]
@rwillians No problem. Thanks for getting back to me. and I hope I can help out in the future.

**Comment by rwillians** [comment]
Thanks @NandoCabralss

I had to pull your branch to fix the version (it was `1.1.32` but was supposed to be `1.1.31`) and update package-lock.json using latest npm. Because of that I had to merge from my own branch instead of yours. Don't worry tho, the only thing this impacts is that this PR won't close automatically therefore I'll have to close it manually (meaning its status will be "closed" as instead of "merged" 😢). You're commits were preserved and duly credited to you, as you can see here in the [commit history](https://github.com/rwillians/express-rescue/commits/master)

Also, I've recently protected the main branch on this repository and it now requires [signed commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits). For your currently opened PR I'll sign them on your behalf, so don't worry about that. For future commits tho, it would be great if you sign them :)

Thanks for your contribution, talk to you on next PRs ;)

**Pull request closed without merging**
